"""Shared UI theme constants for the Textual interface."""

APP_SURFACE = "#ffffff"
UI_INK = "#1f2937"
UI_ACCENT_INK = "#275a45"
UI_BORDER = "#d9e7df"
UI_BORDER_ACTIVE = "#96b9a7"

APP_HEADER_BG = "#1b4332"
APP_HEADER_BG_HOVER = "#24553f"
APP_HEADER_FG = "#ffffff"

SPLIT_HANDLE_COLOR = "#7aa38d"
SPLIT_HANDLE_HOVER_COLOR = "#5f8774"
SPLIT_HANDLE_FOCUS_COLOR = "#4f7464"
SPLIT_HANDLE_HOVER_BG = "#f6fbf8"
SPLIT_HANDLE_FOCUS_BG = "#eef6f1"

SCROLLBAR_COLOR = "#8fd3ac"
SCROLLBAR_COLOR_HOVER = "#74c69d"
SCROLLBAR_COLOR_ACTIVE = "#2d6a4f"
SCROLLBAR_BACKGROUND = "#f8fcf9"
SCROLLBAR_BACKGROUND_HOVER = "#f1f8f3"
SCROLLBAR_BACKGROUND_ACTIVE = "#e7f4ea"

ACCENT_LIGHT_BG = "#d8f3dc"
ACCENT_MID_BG = "#74c69d"
CONTENT_SUBTLE_TEXT = "#44556a"
CONTENT_LIGHT_BG = "#f6fbf8"
CONTENT_LIGHT_BG_ALT = "#eef6f1"
SECTION_HOVER_BG = "#f3fbf5"

BUTTON_FOCUS_BORDER = "#6f9d86"
BUTTON_SUCCESS_HOVER_BG = "#eefaf2"
BUTTON_DEFAULT_HOVER_BG = "#f4fbf6"
BUTTON_DANGER_TEXT = "#a61e4d"
BUTTON_DANGER_BORDER = "#f1aeb5"
BUTTON_DANGER_HOVER_BG = "#fff5f5"
BUTTON_DANGER_HOVER_BORDER = "#e88997"
BUTTON_WARNING_TEXT = "#7c5c00"
BUTTON_WARNING_BG = "#fff9db"
BUTTON_WARNING_HOVER_BG = "#fff4c2"
BUTTON_WARNING_BORDER = "#e9c46a"
BUTTON_WARNING_HOVER_BORDER = "#e0b84d"
BUTTON_WARNING_FOCUS_TEXT = "#523d00"
BUTTON_WARNING_FOCUS_BORDER = "#c99a1d"
BUTTON_FLAT_TEXT = "#1b4332"
BUTTON_FLAT_BORDER = "#d7ebe0"
FOCUS_INK = "#081c15"

INPUT_BORDER = "#b7e4c7"

LIST_ROW_ODD_BG = "#fbfcfd"
LIST_ROW_EVEN_BG = "#eef2f5"

SLATE_BG = "#364152"
SLATE_FG = "#d1d5db"
SLATE_MUTED = "#5b6777"
TOAST_INFO_BORDER = "#37b24d"
TOAST_WARNING_BORDER = "#e9c46a"
TOAST_ERROR_BORDER = "#e03131"

VIEWER_BG = "#111315"
VIEWER_FG = "#f5f7f6"
VIEWER_BORDER = "#2d3b34"
VIEWER_CLOSE_BG = "#1f1f1f"
VIEWER_CLOSE_BG_HOVER = "#2b2b2b"
VIEWER_CLOSE_BORDER_FOCUS = "#5a5a5a"
VIEWER_SCROLLBAR_BG = "#151b18"
VIEWER_SCROLLBAR_BG_HOVER = "#1d2521"
VIEWER_SCROLLBAR_BG_ACTIVE = "#243029"

USAGE_DANGER = "#e03131"
USAGE_WARNING = "#f76707"
USAGE_CAUTION = "#ffd43b"
USAGE_OK = "#37b24d"

TOPBAR_HEIGHT = 3
TOPBAR_CLOSE_WIDTH = 5
BUTTON_HEIGHT = 3
DIALOG_BUTTON_WIDTH = 16
MENU_BUTTON_WIDTH = 28
VIEWER_ACTION_BUTTON_WIDTH = 18
SCROLLBAR_SIZE = 1

SPLIT_HANDLE_WIDTH = 3
MIN_OVERVIEW_WIDTH = 28
TOP_ROW_CHROME_WIDTH = 6
SECTION_MIN_TEXT_WIDTH = 22
SECTION_MIN_ICON_WIDTH = 10

THEME_CSS_TOKENS = f"""
    $app-surface: {APP_SURFACE};
    $ui-ink: {UI_INK};
    $ui-accent-ink: {UI_ACCENT_INK};
    $ui-border: {UI_BORDER};
    $ui-border-active: {UI_BORDER_ACTIVE};
    $app-header-bg: {APP_HEADER_BG};
    $app-header-bg-hover: {APP_HEADER_BG_HOVER};
    $app-header-fg: {APP_HEADER_FG};
    $scrollbar-color: {SCROLLBAR_COLOR};
    $scrollbar-color-hover: {SCROLLBAR_COLOR_HOVER};
    $scrollbar-color-active: {SCROLLBAR_COLOR_ACTIVE};
    $scrollbar-background: {SCROLLBAR_BACKGROUND};
    $scrollbar-background-hover: {SCROLLBAR_BACKGROUND_HOVER};
    $scrollbar-background-active: {SCROLLBAR_BACKGROUND_ACTIVE};
"""
